// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CreaterClient is the client API for Creater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreaterClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Empty, error)
}

type createrClient struct {
	cc grpc.ClientConnInterface
}

func NewCreaterClient(cc grpc.ClientConnInterface) CreaterClient {
	return &createrClient{cc}
}

func (c *createrClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Creater/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreaterServer is the server API for Creater service.
// All implementations must embed UnimplementedCreaterServer
// for forward compatibility
type CreaterServer interface {
	Create(context.Context, *CreateRequest) (*Empty, error)
	mustEmbedUnimplementedCreaterServer()
}

// UnimplementedCreaterServer must be embedded to have forward compatible implementations.
type UnimplementedCreaterServer struct {
}

func (UnimplementedCreaterServer) Create(context.Context, *CreateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCreaterServer) mustEmbedUnimplementedCreaterServer() {}

// UnsafeCreaterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreaterServer will
// result in compilation errors.
type UnsafeCreaterServer interface {
	mustEmbedUnimplementedCreaterServer()
}

func RegisterCreaterServer(s grpc.ServiceRegistrar, srv CreaterServer) {
	s.RegisterService(&Creater_ServiceDesc, srv)
}

func _Creater_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreaterServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Creater/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreaterServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Creater_ServiceDesc is the grpc.ServiceDesc for Creater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Creater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Creater",
	HandlerType: (*CreaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Creater_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task_manager.proto",
}
